Types and variables
ArnisM11/codelex11 pull request #1
Opened 2023-02-19 16:37 UTC by ArnisM11

done

2023-02-19 16:42 UTC, EdgarsSalmins commented on csharp-basics/exercises/TypesAndVariables/Casting/Program.cs
> +            int a = 1;
te tipus mainīgajiem nevar mainīt.. :) jākasto. :)

2023-02-19 16:43 UTC, EdgarsSalmins commented on csharp-basics/exercises/TypesAndVariables/Casting/Program.cs
> +            int a = 1;
te tas pats.

2023-02-19 16:44 UTC, EdgarsSalmins commented on csharp-basics/exercises/TypesAndVariables/MoreVariablesAndPrinting/Program.cs
> +            string Name, Eyes, Teeth, Hair;
define mainīgo kur piešķir vērtību. :)

2023-02-20 09:39 UTC, ausmoons requested changes

2023-02-20 09:39 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Casting/Program.cs
Šos mainīt nevar

2023-02-20 09:39 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/MoreVariablesAndPrinting/Program.cs
> +            string Name = "Zed A. Shaw";
Nosaukumi ar mazo burtu šeit

2023-02-20 18:26 UTC, ArnisM11 commented
Atkal nezinu kādā veidā šajā repositorijā pazuduši šie jaunizveidotie faili, viss rakstītais, īsti arī nesanāk revertot pēc PR iesniegtos commitus. Saprotu kas izdarīts nepareizi, vai drīkstu ietaupīt savu laiku un pacietību un neiesniegt mājasdarba labojumu? Iesniedzu Arithmetics mājasdarbu, tur, šķiet ka visam vajadzētu būt pareizāk izpildītam, bez liekiem commitiem, apsolos vairs nesajukt, neiecommitot nepareizajā branchaa

2023-02-27 07:22 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/MoreVariablesAndPrinting/Program.cs
> +            string Name = "Zed A. Shaw";
Tev vairs nav failu šeit. Iekopē kaut vai no history

2023-03-15 19:56 UTC, ausmoons approved these changes
Izlabo casting uzd un tad var mergot

2023-03-15 19:56 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Casting/Program.cs
Šis nav izlabots kā vajadzēja

2023-03-15 22:52 UTC, merged