Arrays
ArnisM11/codelex11 pull request #4
Opened 2023-03-02 21:38 UTC by ArnisM11

Atvainojos par kavēšanos. Plānotais 4 dienu ceļojums negaidīti pagarinājās vēl par 3 dienām, līdz ar to iesniedzu cik ātri sanāca. Ceru uz sapratni.

2023-03-05 05:11 UTC, ausmoons requested changes
Sakārto visus failus

2023-03-05 05:11 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Exercise1/Program.cs
> -        //TODO: Write a C# program to sort a numeric array and a string array.
Tev pie solution nerāda visus projektus 
![image](https://user-images.githubusercontent.com/53189160/222942618-92f0cb43-49b8-40dc-818d-304f6a2e7595.png)

2023-03-05 05:11 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Exercise10/Program.cs
> +        static void printResult(int[] array)
Metodes ar lielo burtu

2023-03-05 05:11 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Exercise2/Program.cs
> +            for (int i = minNumber; i<=maxNumber; i++) {
{ jaunā rindā

2023-03-05 05:11 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Exercise4/Program.cs
> +            for (int i = 0;i<myArray.Length;i++) {
Pārbaudi visur, lai { sāktos jaunā rindā

2023-03-05 05:11 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Exercise4/Program.cs
> +
Lieka tukša rinda

2023-03-05 05:11 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Exercise6/Program.cs
> +            }
Pēc } tukša rinda

2023-03-05 05:11 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Exercise8/Program.cs
> +        public static string randomWordStripes(string word)
Metodes ar lielo burtu un starp tām tukša rinda

2023-03-05 05:11 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +            } while (!checkWinner(isTurn));
Pēc while prasītos jauna rinda. Duadz koda bez tukšām rindām

2023-03-05 05:11 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +                if (checkTie())
Starp dažādiem if tukša rinda

2023-03-05 05:11 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +        public static bool checkWinner(char isTurn)
Metodes ar lielo burtu

2023-03-05 05:11 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +            if (board[0, 0] == isTurn && board[1, 1] == isTurn && board[2, 2] == isTurn && board[0, 0] != ' ' && board[1, 1] != ' ' && board[2, 2] != ' ') return true;
Pēc } tukša rinda

2023-03-05 17:13 UTC, ausmoons approved these changes
Nākmreiz taisi jaunus projektus pareizi, nevis kā jaunu solution

2023-03-06 16:03 UTC, ArnisM11 commented
> 
Saprotu, tiks darīts! ;)

2023-03-06 16:03 UTC, merged