Classes and objects
ArnisM11/codelex11 pull request #6
Opened 2023-03-08 15:40 UTC by ArnisM11

Classes done

2023-03-10 17:53 UTC, ausmoons requested changes

2023-03-10 17:53 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Account/Account.cs
> +
Liekas tukšas rindas nevajag atstāt

2023-03-10 17:53 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Account/Program.cs
> +        public static void Transfer(Account from, Account to, double howMuch)
Starp metodēm tukša rinda

2023-03-10 17:53 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise1/Program.cs
> +            this.priceAtStart = priceAtStart;
Private

2023-03-10 17:53 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise1/Program.cs
> +        public void ChangePrice(double newPrice)
Starp metodēm tukša rinda

2023-03-10 17:53 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise12/Student.cs
> +public class Student : IStudent
Katra klase, interface savā failā

2023-03-10 17:53 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise12/Testpaper.cs
> +        Subject = subject;
Sakārto visur tab

2023-03-10 17:53 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise12/Testpaper.cs
> +        Subject = subject;
Private?

2023-03-10 17:53 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise13/Smoothie.cs
> +				case ("Strawberries"):
Tab nav ok

2023-03-10 17:53 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise13/Smoothie.cs
> +			}
Pēc } tukša rinda. Pārbaudi visus failus

2023-03-10 17:53 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/VideoStore/Video.cs
> +            _available = true;
private

2023-03-12 15:44 UTC, ArnisM11 commented on csharp-basics/exercises/ClassesAndObjects/VideoStore/Video.cs
> +            _available = true;
Klases konstruktoram būtu jābūt private?

2023-03-14 21:10 UTC, ausmoons requested changes

2023-03-14 21:10 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/VideoStore/Video.cs
> +            this.Title = title;
Kāpēc tu nevari atstāt šo  public Video(string title)
        {
            _title = title;
        }?

2023-03-14 21:10 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/VideoStore/Video.cs
> +            _available = true;
Nē. Es par propertiju domāju. Bet Tilte netiek mainīts, tad var palikt tikai kā public

2023-03-14 21:10 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise12/Testpaper.cs
> +            this.Subject = subject;
Bez this

2023-03-14 21:10 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise1/Program.cs
> +        public double _priceAtStart;
Tu raksti kā private, bet sauc public. Un visur var bez this

2023-03-14 21:10 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise13/Smoothie.cs
> +		public double GetPrice()
Sakārto tab

2023-03-14 21:10 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise14/Date.cs
> +		CultureInfo nlCulture = new CultureInfo("nl-NL");
Visur pārbaudi tab

2023-03-14 21:10 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise3/FuelGauge.cs
> +	public void Fill()
Starp metodēm tukša rinda

2023-03-14 21:10 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise4/Program.cs
> +        public string title;
Ja public tad ar lielo burtu un ar get, set. Sakārto visur nosaukumus

2023-03-14 21:10 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise6/Program.cs
> +        public string Sex
Tev sex jau ir public. Kam tev vēl atsevišķu Sex?

2023-03-14 21:10 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise6/Program.cs
> +        {
Katra klase savā failā

2023-03-14 21:10 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise7/Program.cs
> +
Tev tagad te ir 2 klases vienā, bet pat nerakstot abas klases. Sakārto, lai ir atsevišks program.cs un SavingsAccount.cs

2023-03-14 21:10 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise9/BankAccount.cs
> +        public string name;
Public visur ar lielo burtu

2023-03-18 17:23 UTC, ausmoons approved these changes

2023-03-18 17:23 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise6/Dog.cs
> +            this.name = name;
Bez this un public ar lielo burtu

2023-03-18 17:23 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/VideoStore/Video.cs
>              this._available = true;
Noņem visur this

2023-03-20 12:52 UTC, merged