Polymorphism
ArnisM11/codelex11 pull request #8
Opened 2023-03-16 15:52 UTC by ArnisM11

Polymorphism done

2023-03-19 12:52 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/AdApp/AdApp.cs
> +            this._dimensions= string.Empty;
this nevajag likt. :)

2023-03-19 13:09 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/AdApp/AdApp.cs
> +            return base.Cost();
vai tad cena nebija jaaprēķina citādi kā pašam Advert?

2023-03-19 13:11 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Exercise3/Person.cs
> +            result += "Last name : " + _lastName + "\n";
\n vietā var lietot Environment.NewLine

2023-03-19 13:12 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Hierarchy/Animal.cs
> +        public string animalName { get; set; }
public mainigajiem bija citāds naming.

2023-03-19 13:12 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Hierarchy/Animal.cs
> +        public void eat(Food food)
kapēc nav abstract?

2023-03-19 13:13 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Hierarchy/Animal.cs
> +        public void makeSound()
vajadzēja būt abstract?

2023-03-19 13:13 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Hierarchy/Cat.cs
> +        new public void makeSound()
un te būs override ja animal klasē būs abstract. :)

2023-03-19 13:14 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Hierarchy/Felime.cs
> +        new public void makeSound()
metožu nosaukumi ar lielo burtu

2023-03-19 13:14 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Hierarchy/Mouse.cs
> +            else foodEaten = food.quantity;
bez else. :) ja ēdiens nav gaļa tad visi gadījumi pārējie darbojas.

2023-03-19 13:15 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Hierarchy/Program.cs
> +            switch (type)
gribi pamēģināt šo paskatīties kā dinamiski risināt?

2023-03-19 13:22 UTC, EdgarsSalmins requested changes
salabo visam naming... metožu un private public nosaukumi... 
paskaties kurām metodēm vajadzētu būt apbstract.

2023-03-20 13:21 UTC, ArnisM11 commented on csharp-basics/exercises/Polymorphism/Hierarchy/Animal.cs
> +        public void eat(Food food)
Pašām metodēm eat() un makeSound() jābūt abstract?

2023-03-27 10:56 UTC, merged